apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

# The names inside the patches must match Resource names that are already
# loaded. Small patches that do one thing are recommended.
patchesStrategicMerge:
- custom-env.yaml

configMapGenerator:
- name: example-configmap-1
  files:
  - application.properties

secretGenerator:
- name: example-secret-1
  files:
  - password.txt
