apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patchesStrategicMerge:
- custom-env.yaml

configMapGenerator:
- name: example-configmap-1
  files:
  - application.properties

secretGenerator:
- name: example-secret-1
  files:
  - password.txt
